### ISSUE TITLE
Does not work with the current version of ptpython

### ISSUE THREAD

**Issue by techdragon** [opn-oss/autobahn-python-repl#4]
I've added a PR #3 for the last version of the ptpython where the program starts, but the program is still really broken using this version. Can you either pin all the dependencies correctly, or update this to use the new version of ptpython

I'd try to make a PR for the changes, but ptpython does not appear to have any documentation on how to use it the way you have done, which makes working out how to update your code quite a lot harder than I expected.

**Comment by OOPMan** [comment]
@techdragon Thanks for the PR, will merge. Originally this program was part of another project which was used as a library and hence its dependencies weren't pinned as a result. When I split it off I was in a bit of a hurry and forgot to pin. Thanks!
